<div id="checkout-review" class="firecheckout-section">
    <div class="block-title"><span><?php echo $this->__('Checkout Review') ?></span></div>
    <?php $agreements = $this->getChildHtml('agreements') ?>
    <?php if (!empty($agreements)) : ?>
        <div id="agreements-wrapper">
            <?php echo $agreements; ?>
        </div>
    <?php endif; ?>
    <div id="checkout-review-load">
        <?php echo $this->getChildHtml('info') ?>
    </div>
    <?php
    $html = $this->getChildHtml('review_after');
    if ($html || $blockId = Mage::getStoreConfig('firecheckout/additional_content/reviewtable_after')) : ?>
        <div class="firecheckout-items-after">
            <?php echo $blockId ? $this->getLayout()->createBlock('cms/block')->setBlockId($blockId)->toHtml() : ''; ?>
            <?php echo $html ?>
        </div>
    <?php endif; ?>
    <script type="text/javascript">
        //<![CDATA[
            review = new Review(); // dummy class for various payment methods
        //]]>
    </script>
    <div id="checkout-review-submit">
        <div class="buttons-set" id="review-buttons-container">
            <button type="button" id="review-buttons-container-button" title="<?php echo $this->__('Place Order') ?>" class="button btn-checkout" onclick="return false;"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
            <span class="please-wait" id="review-please-wait" style="display:none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
            </span>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('review-buttons-container-button').observe('click', function() {
        if(payment.currentMethod == 'iways_paypalplus_payment') {
            if (checkout.validate() && payment.currentMethod == 'iways_paypalplus_payment') {
                var form = $('firecheckout-form');
                checkout.setLoadWaiting(true);
                $('review-please-wait').show();
                new Ajax.Request('<?php echo Mage::helper('iways_paypalplus')->getUrl('paypalplus/index/patch'); ?>', {
                    method: 'post',
                    parameters: form.serialize(),
                    onSuccess: function (transport) {
                        if (transport.status == 200) {
                            var response = transport.responseText.evalJSON();
                            if (response.status == 'success') {
                                window.ppp.doCheckout();
                            }
                        }
                    },
                    onFailure: function (transport) {
                        checkout.setLoadWaiting(false);
                        $('review-please-wait').hide();
                    }
                });
            }
        } else {
            checkout.save();
        }
    });
</script>